<?php
/**
 * Tanguy GITON Copyright (c) 2016.
 */

namespace AppBundle\Repository;

use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends SortableRepository
{

}
