imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes: ['bootstrap_3_horizontal_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

easy_admin:
    entities:
        - AppBundle\Entity\Newsletter
        - AppBundle\Entity\Rubrique
        - AppBundle\Entity\Post
        - AppBundle\Entity\Type

stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            sortable: true

assetic:
    debug:          "%kernel.debug%"
    use_controller: "%kernel.debug%"
    node: "%node_path%"
    filters:
        cssrewrite:
            apply_to: '\.css$'
        uglifycss:
            bin: "%uglifycss_path%"
            apply_to: '\.css$'
        uglifyjs2:
            bin: "%uglifyjs2_path%"
            apply_to:   '\.js$'
        less:
            node_paths: "%node_paths_path%"
            apply_to:   '\.less$'
    assets:
        boostrap:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less"
        jqueryjs:
            inputs:
                - "%kernel.root_dir%/../vendor/jquery/jquery/jquery-2.2.4.js"
        bootstrapjs:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.js"
        font_awesome:
            inputs:
                - '%kernel.root_dir%/../vendor/components/font-awesome/css/font-awesome.css'
        font-awesome-otf:
                inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/FontAwesome.otf'
                output: 'fonts/FontAwesome.otf'
        font-awesome-eot:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.eot'
            output: 'fonts/fontawesome-webfont.eot'
        font-awesome-svg:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.svg'
            output: 'fonts/fontawesome-webfont.svg'
        font-awesome-ttf:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.ttf'
            output: 'fonts/fontawesome-webfont.ttf'
        font-awesome-woff:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff'
            output: 'fonts/fontawesome-webfont.woff'
        font-awesome-woff2:
            inputs: '%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff2'
            output: 'fonts/fontawesome-webfont.woff2'
        glyphicons-eot:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.eot'
            output: 'fonts/glyphicons-halflings-regular.eot'
        glyphicons-svg:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.svg'
            output: 'fonts/glyphicons-halflings-regular.svg'
        glyphicons-ttf:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.ttf'
            output: 'fonts/glyphicons-halflings-regular.ttf'
        glyphicons-woff:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff'
            output: 'fonts/glyphicons-halflings-regular.woff'
        glyphicons-woff2:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff2'
            output: 'fonts/glyphicons-halflings-regular.woff2'
        jqueryuijs:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jqueryui/jquery-ui.js'
        simple-mde-js:
            inputs:
                - '%kernel.root_dir%/../bower_components/simplemde/debug/simplemde.js'
        simple-mde-css:
            inputs:
                - '%kernel.root_dir%/../bower_components/simplemde/debug/simplemde.css'